name: test

#https://stackoverflow.com/questions/62846375/perform-github-action-when-trying-to-merge-branch
on: 
  push:
    - master
  pull_request:
    branches:
      - master
    types: 
      - ready_for_review
      - review_requested

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: npx jest